In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3))
c = np.arange(0, 10, 2)

In [7]:
print(a[0])
print(a[1:3])
print(a[a>2])

1
[2 3]
[3 4]


In [8]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print(x + y)       
print(x * y)        
print(np.mean(x))  


[11 22 33]
[10 40 90]
20.0


In [9]:
print(x**2)
print((x - np.mean(x)) / np.std(x))
print(np.dot(x, y))


[100 400 900]
[-1.22474487  0.          1.22474487]
140


In [10]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Element at row 1, column 2:", matrix[0, 1])
print("Element at row 2, column 3:", matrix[1, 2])

[[1 2 3]
 [4 5 6]]
Element at row 1, column 2: 2
Element at row 2, column 3: 6
